app:
  name: "iot_student_presence_tool"
  description: "A FastAPI application with ESP32 wifi and cable connection support"

postgres_db:
  user: postgres.pzimhcmuhynltrrhkvwc
  host: aws-0-eu-central-1.pooler.supabase.com
  port: 6543
  dbname: postgres

esp_32_connection: wifi # or "usb"

# Environment configuration
environment:
  development:
    debug: true
    cors_origins:
      - http://localhost
      - http://localhost:8000
  testing:
    debug: true
    cors_origins:
      - http://localhost
      - http://localhost:8000
  production:
    debug: false
    cors_origins:
      - https://example.com